package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/geniusrabbit/blaze-api/server/graphql/connectors"
	basemodels "github.com/geniusrabbit/blaze-api/server/graphql/models"
)

// DeleteAuthSession is the resolver for the deleteAuthSession field.
func (r *mutationResolver) DeleteAuthSession(ctx context.Context, id uint64) (*basemodels.AuthSession, error) {
	return r.authsessions.DeleteAuthSession(ctx, id)
}

// AuthSession is the resolver for the authSession field.
func (r *queryResolver) AuthSession(ctx context.Context, id uint64) (*basemodels.AuthSession, error) {
	return r.authsessions.AuthSession(ctx, id)
}

// ListAuthSessions is the resolver for the listAuthSessions field.
func (r *queryResolver) ListAuthSessions(ctx context.Context, filter *basemodels.AuthSessionListFilter, order []*basemodels.AuthSessionListOrder, page *basemodels.Page) (*connectors.CollectionConnection[*basemodels.AuthSession], error) {
	return r.authsessions.ListAuthSessions(ctx, filter, order, page)
}
