package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"fmt"

	"github.com/geniusrabbit/blaze-api/server/graphql/models"
)

// Notes is the resolver for the notes field.
func (r *userResolver) Notes(ctx context.Context, obj *models.User) (*string, error) {
	panic(fmt.Errorf("not implemented: Notes - notes"))
}

// AccountID is the resolver for the accountID field.
func (r *userListFilterResolver) AccountID(ctx context.Context, obj *models.UserListFilter, data []uint64) error {
	panic(fmt.Errorf("not implemented: AccountID - accountID"))
}

// Roles is the resolver for the roles field.
func (r *userListFilterResolver) Roles(ctx context.Context, obj *models.UserListFilter, data []uint64) error {
	panic(fmt.Errorf("not implemented: Roles - roles"))
}

// RegistrationDate is the resolver for the registrationDate field.
func (r *userListOrderResolver) RegistrationDate(ctx context.Context, obj *models.UserListOrder, data *models.Ordering) error {
	panic(fmt.Errorf("not implemented: RegistrationDate - registrationDate"))
}

// Country is the resolver for the country field.
func (r *userListOrderResolver) Country(ctx context.Context, obj *models.UserListOrder, data *models.Ordering) error {
	panic(fmt.Errorf("not implemented: Country - country"))
}

// Manager is the resolver for the manager field.
func (r *userListOrderResolver) Manager(ctx context.Context, obj *models.UserListOrder, data *models.Ordering) error {
	panic(fmt.Errorf("not implemented: Manager - manager"))
}
