package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"fmt"

	models1 "github.com/geniusrabbit/blaze-api/example/api/internal/server/graphql/models"
	"github.com/geniusrabbit/blaze-api/server/graphql/connectors"
	"github.com/geniusrabbit/blaze-api/server/graphql/models"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input models1.UserCreateInput) (*models1.UserPayload, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uint64, input models1.UserUpdateInput) (*models1.UserPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// ApproveUser is the resolver for the approveUser field.
func (r *mutationResolver) ApproveUser(ctx context.Context, id uint64, msg *string) (*models1.UserPayload, error) {
	panic(fmt.Errorf("not implemented: ApproveUser - approveUser"))
}

// RejectUser is the resolver for the rejectUser field.
func (r *mutationResolver) RejectUser(ctx context.Context, id uint64, msg *string) (*models1.UserPayload, error) {
	panic(fmt.Errorf("not implemented: RejectUser - rejectUser"))
}

// CurrentUser is the resolver for the currentUser field.
func (r *queryResolver) CurrentUser(ctx context.Context) (*models1.UserPayload, error) {
	panic(fmt.Errorf("not implemented: CurrentUser - currentUser"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uint64, username string) (*models1.UserPayload, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context, filter *models1.UserListFilter, order []*models1.UserListOrder, page *models.Page) (*connectors.CollectionConnection[*models1.User], error) {
	panic(fmt.Errorf("not implemented: ListUsers - listUsers"))
}
