package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	models1 "github.com/geniusrabbit/blaze-api/example/api/internal/server/graphql/models"
	"github.com/geniusrabbit/blaze-api/server/graphql/connectors"
	"github.com/geniusrabbit/blaze-api/server/graphql/models"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input models1.UserCreateInput) (*models1.UserPayload, error) {
	return r.users.CreateUser(ctx, &input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uint64, input models1.UserUpdateInput) (*models1.UserPayload, error) {
	return r.users.UpdateUser(ctx, id, &input)
}

// ApproveUser is the resolver for the approveUser field.
func (r *mutationResolver) ApproveUser(ctx context.Context, id uint64, msg *string) (*models1.UserPayload, error) {
	return r.users.ApproveUser(ctx, id, msg)
}

// RejectUser is the resolver for the rejectUser field.
func (r *mutationResolver) RejectUser(ctx context.Context, id uint64, msg *string) (*models1.UserPayload, error) {
	return r.users.RejectUser(ctx, id, msg)
}

// CurrentUser is the resolver for the currentUser field.
func (r *queryResolver) CurrentUser(ctx context.Context) (*models1.UserPayload, error) {
	return r.users.CurrentUser(ctx)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uint64, username string) (*models1.UserPayload, error) {
	return r.users.User(ctx, id, username)
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context, filter *models1.UserListFilter, order []*models1.UserListOrder, page *models.Page) (*connectors.CollectionConnection[*models1.User], error) {
	return r.users.ListUsers(ctx, filter, order, page)
}
