package resolvers


			// This file will be automatically regenerated based on the schema, any resolver
			// implementations
			// will be copied through when generating and any unknown code will be moved to the end.
			// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
"context"
"fmt"
"io"
"strconv"
"time"
"sync"
"errors"
"bytes"
gqlparser "github.com/vektah/gqlparser/v2"
"github.com/vektah/gqlparser/v2/ast"
"github.com/99designs/gqlgen/graphql"
"github.com/99designs/gqlgen/graphql/introspection"
"github.com/geniusrabbit/blaze-api/server/graphql/models"
"github.com/geniusrabbit/blaze-api/example/api/internal/server/graphql/generated")



















		//CreateUser is the resolver for the createUser field.
		func (r *mutationResolver) CreateUser(ctx context.Context, input models.UserCreateInput) (*models.UserPayload, error){
			panic(fmt.Errorf("not implemented: CreateUser - createUser"))
		}

		//UpdateUser is the resolver for the updateUser field.
		func (r *mutationResolver) UpdateUser(ctx context.Context, id uint64, input models.UserUpdateInput) (*models.UserPayload, error){
			panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
		}

		//ApproveUser is the resolver for the approveUser field.
		func (r *mutationResolver) ApproveUser(ctx context.Context, id uint64, msg *string) (*models.UserPayload, error){
			panic(fmt.Errorf("not implemented: ApproveUser - approveUser"))
		}

		//RejectUser is the resolver for the rejectUser field.
		func (r *mutationResolver) RejectUser(ctx context.Context, id uint64, msg *string) (*models.UserPayload, error){
			panic(fmt.Errorf("not implemented: RejectUser - rejectUser"))
		}

		//CurrentUser is the resolver for the currentUser field.
		func (r *queryResolver) CurrentUser(ctx context.Context) (*models.UserPayload, error){
			panic(fmt.Errorf("not implemented: CurrentUser - currentUser"))
		}

		//User is the resolver for the user field.
		func (r *queryResolver) User(ctx context.Context, id uint64, username string) (*models.UserPayload, error){
			panic(fmt.Errorf("not implemented: User - user"))
		}

		//ListUsers is the resolver for the listUsers field.
		func (r *queryResolver) ListUsers(ctx context.Context, filter *models.UserListFilter, order []*models.UserListOrder, page *models.Page) (*invalid type, error){
			panic(fmt.Errorf("not implemented: ListUsers - listUsers"))
		}

		//TotalCount is the resolver for the totalCount field.
		func (r *userConnectionResolver) TotalCount(ctx context.Context, obj *invalid type) (int, error){
			panic(fmt.Errorf("not implemented: TotalCount - totalCount"))
		}

		//List is the resolver for the list field.
		func (r *userConnectionResolver) List(ctx context.Context, obj *invalid type) ([]*models.User, error){
			panic(fmt.Errorf("not implemented: List - list"))
		}

		//PageInfo is the resolver for the pageInfo field.
		func (r *userConnectionResolver) PageInfo(ctx context.Context, obj *invalid type) (*models.PageInfo, error){
			panic(fmt.Errorf("not implemented: PageInfo - pageInfo"))
		}


// User returns generated.UserResolver implementation.
	func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }
// UserConnection returns generated.UserConnectionResolver implementation.
	func (r *Resolver) UserConnection() generated.UserConnectionResolver { return &userConnectionResolver{r} }
// UserListFilter returns generated.UserListFilterResolver implementation.
	func (r *Resolver) UserListFilter() generated.UserListFilterResolver { return &userListFilterResolver{r} }
// UserListOrder returns generated.UserListOrderResolver implementation.
	func (r *Resolver) UserListOrder() generated.UserListOrderResolver { return &userListOrderResolver{r} }


type userResolver struct { *Resolver }
type userConnectionResolver struct { *Resolver }
type userListFilterResolver struct { *Resolver }
type userListOrderResolver struct { *Resolver }



