// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"github.com/geniusrabbit/blaze-api/server/graphql/models"
)

type DirectAccessTokenConnection struct {
	// Total count of DirectAccessToken objects
	TotalCount int `json:"totalCount"`
	// Edges for the DirectAccessTokenConnection
	Edges []*models.DirectAccessTokenEdge `json:"edges,omitempty"`
	// List of DirectAccessToken objects
	List []*models.DirectAccessToken `json:"list,omitempty"`
	// PageInfo for the DirectAccessTokenConnection
	PageInfo *models.PageInfo `json:"pageInfo"`
}
