// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"

	"github.com/geniusrabbit/blaze-api/server/graphql/models"
)

// Account is a company account that can be used to login to the system.
// Core fields only — extend in consumer schema via `extend type Account`.
type Account struct {
	// The primary key of the Account
	ID uint64 `json:"ID"`
	// Status of Account active
	Status models.ApproveStatus `json:"status"`
	// Message which defined during user approve/rejection process
	StatusMessage *string   `json:"statusMessage,omitempty"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	Title         string    `json:"title"`
	Description   string    `json:"description"`
	// logoURI is an URL string that references a logo for the client.
	LogoURI string `json:"logoURI"`
	// policyURI is a URL string that points to a human-readable privacy policy document.
	PolicyURI string `json:"policyURI"`
	// termsOfServiceURI is a URL string that points to a human-readable terms of service document.
	TermsOfServiceURI string `json:"termsOfServiceURI"`
	// clientURI is an URL string of a web page providing information about the client.
	ClientURI string `json:"clientURI"`
	// contacts is a array of strings representing ways to contact people responsible for this client.
	Contacts []string `json:"contacts,omitempty"`
}

type AccountCreateInput struct {
	Status            *models.ApproveStatus `json:"status,omitempty"`
	Title             *string               `json:"title,omitempty"`
	Description       *string               `json:"description,omitempty"`
	LogoURI           *string               `json:"logoURI,omitempty"`
	PolicyURI         *string               `json:"policyURI,omitempty"`
	TermsOfServiceURI *string               `json:"termsOfServiceURI,omitempty"`
	ClientURI         *string               `json:"clientURI,omitempty"`
	Contacts          []string              `json:"contacts,omitempty"`
}

type AccountListFilter struct {
	ID     []uint64               `json:"ID,omitempty"`
	UserID []uint64               `json:"UserID,omitempty"`
	Status []models.ApproveStatus `json:"status,omitempty"`
	Title  []string               `json:"title,omitempty"`
}

type AccountListOrder struct {
	ID        *models.Ordering `json:"ID,omitempty"`
	Status    *models.Ordering `json:"status,omitempty"`
	CreatedAt *models.Ordering `json:"createdAt,omitempty"`
	UpdatedAt *models.Ordering `json:"updatedAt,omitempty"`
	Title     *models.Ordering `json:"title,omitempty"`
}

// AccountPayload wrapper to access of Account oprtation results
type AccountPayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID string `json:"clientMutationID"`
	// Account ID operation result
	AccountID uint64 `json:"accountID"`
	// Account object accessor
	Account *Account `json:"account,omitempty"`
}

type AccountUpdateInput struct {
	Status            *models.ApproveStatus `json:"status,omitempty"`
	Title             *string               `json:"title,omitempty"`
	Description       *string               `json:"description,omitempty"`
	LogoURI           *string               `json:"logoURI,omitempty"`
	PolicyURI         *string               `json:"policyURI,omitempty"`
	TermsOfServiceURI *string               `json:"termsOfServiceURI,omitempty"`
	ClientURI         *string               `json:"clientURI,omitempty"`
	Contacts          []string              `json:"contacts,omitempty"`
}

// User represents a user object of the system.
// Core fields only — extend in consumer schema via `extend type User`.
type User struct {
	// The primary key of the user
	ID uint64 `json:"ID"`
	// Status of user active
	Status models.ApproveStatus `json:"status"`
	// Message which defined during user approve/rejection process
	StatusMessage *string   `json:"statusMessage,omitempty"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	// Email address (optional trait — present only when user.Email is embedded).
	Email string `json:"email"`
	// Unique username (separate from email, optional trait).
	Username string  `json:"username"`
	Notes    *string `json:"notes,omitempty"`
}

type UserCreateInput struct {
	Status   *models.ApproveStatus `json:"status,omitempty"`
	Email    string                `json:"email"`
	Username *string               `json:"username,omitempty"`
}

// UserListFilter implements filter for user list query
type UserListFilter struct {
	ID        []uint64 `json:"ID,omitempty"`
	Emails    []string `json:"emails,omitempty"`
	AccountID []uint64 `json:"accountID,omitempty"`
	Roles     []uint64 `json:"roles,omitempty"`
}

// UserListOrder implements order for user list query
type UserListOrder struct {
	ID               *models.Ordering `json:"ID,omitempty"`
	Status           *models.Ordering `json:"status,omitempty"`
	CreatedAt        *models.Ordering `json:"createdAt,omitempty"`
	UpdatedAt        *models.Ordering `json:"updatedAt,omitempty"`
	Email            *models.Ordering `json:"email,omitempty"`
	Username         *models.Ordering `json:"username,omitempty"`
	RegistrationDate *models.Ordering `json:"registrationDate,omitempty"`
	Country          *models.Ordering `json:"country,omitempty"`
	Manager          *models.Ordering `json:"manager,omitempty"`
}

// UserPayload wrapper to access of user oprtation results
type UserPayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID string `json:"clientMutationID"`
	// User ID operation result
	UserID uint64 `json:"userID"`
	// User object accessor
	User *User `json:"user,omitempty"`
}

type UserUpdateInput struct {
	Status *models.ApproveStatus `json:"status,omitempty"`
	Email  *string               `json:"email,omitempty"`
}
