// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source usecase.go -package mocks -destination mocks/usecase.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	account "github.com/geniusrabbit/blaze-api/repository/account"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockUsecase) Count(ctx context.Context, filter *account.Filter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockUsecaseMockRecorder) Count(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockUsecase)(nil).Count), ctx, filter)
}

// Delete mocks base method.
func (m *MockUsecase) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUsecaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUsecase)(nil).Delete), ctx, id)
}

// FetchList mocks base method.
func (m *MockUsecase) FetchList(ctx context.Context, filter *account.Filter, order *account.ListOrder, p *account.Pagination) ([]*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchList", ctx, filter, order, p)
	ret0, _ := ret[0].([]*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchList indicates an expected call of FetchList.
func (mr *MockUsecaseMockRecorder) FetchList(ctx, filter, order, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchList", reflect.TypeOf((*MockUsecase)(nil).FetchList), ctx, filter, order, p)
}

// Get mocks base method.
func (m *MockUsecase) Get(ctx context.Context, id uint64) (*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUsecaseMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUsecase)(nil).Get), ctx, id)
}

// Register mocks base method.
func (m *MockUsecase) Register(ctx context.Context, ownerObj *account.User, accountObj *account.Account, password string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, ownerObj, accountObj, password)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUsecaseMockRecorder) Register(ctx, ownerObj, accountObj, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUsecase)(nil).Register), ctx, ownerObj, accountObj, password)
}

// Store mocks base method.
func (m *MockUsecase) Store(ctx context.Context, arg1 *account.Account) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockUsecaseMockRecorder) Store(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUsecase)(nil).Store), ctx, arg1)
}

// MockMemberUsecase is a mock of MemberUsecase interface.
type MockMemberUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockMemberUsecaseMockRecorder
	isgomock struct{}
}

// MockMemberUsecaseMockRecorder is the mock recorder for MockMemberUsecase.
type MockMemberUsecaseMockRecorder struct {
	mock *MockMemberUsecase
}

// NewMockMemberUsecase creates a new mock instance.
func NewMockMemberUsecase(ctrl *gomock.Controller) *MockMemberUsecase {
	mock := &MockMemberUsecase{ctrl: ctrl}
	mock.recorder = &MockMemberUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberUsecase) EXPECT() *MockMemberUsecaseMockRecorder {
	return m.recorder
}

// CountMembers mocks base method.
func (m *MockMemberUsecase) CountMembers(ctx context.Context, filter *account.MemberFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMembers", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMembers indicates an expected call of CountMembers.
func (mr *MockMemberUsecaseMockRecorder) CountMembers(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMembers", reflect.TypeOf((*MockMemberUsecase)(nil).CountMembers), ctx, filter)
}

// FetchListMembers mocks base method.
func (m *MockMemberUsecase) FetchListMembers(ctx context.Context, filter *account.MemberFilter, order *account.MemberListOrder, p *account.Pagination) ([]*account.AccountMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchListMembers", ctx, filter, order, p)
	ret0, _ := ret[0].([]*account.AccountMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchListMembers indicates an expected call of FetchListMembers.
func (mr *MockMemberUsecaseMockRecorder) FetchListMembers(ctx, filter, order, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchListMembers", reflect.TypeOf((*MockMemberUsecase)(nil).FetchListMembers), ctx, filter, order, p)
}

// InviteMember mocks base method.
func (m *MockMemberUsecase) InviteMember(ctx context.Context, accountID uint64, email string, roles ...string) (*account.AccountMember, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, accountID, email}
	for _, a := range roles {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InviteMember", varargs...)
	ret0, _ := ret[0].(*account.AccountMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InviteMember indicates an expected call of InviteMember.
func (mr *MockMemberUsecaseMockRecorder) InviteMember(ctx, accountID, email any, roles ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, accountID, email}, roles...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteMember", reflect.TypeOf((*MockMemberUsecase)(nil).InviteMember), varargs...)
}

// LinkMember mocks base method.
func (m *MockMemberUsecase) LinkMember(ctx context.Context, arg1 *account.Account, isAdmin bool, members ...*account.User) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, arg1, isAdmin}
	for _, a := range members {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LinkMember", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkMember indicates an expected call of LinkMember.
func (mr *MockMemberUsecaseMockRecorder) LinkMember(ctx, arg1, isAdmin any, members ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, arg1, isAdmin}, members...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkMember", reflect.TypeOf((*MockMemberUsecase)(nil).LinkMember), varargs...)
}

// SetAccountMemeberRoles mocks base method.
func (m *MockMemberUsecase) SetAccountMemeberRoles(ctx context.Context, accountID, userID uint64, roles ...string) (*account.AccountMember, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, accountID, userID}
	for _, a := range roles {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetAccountMemeberRoles", varargs...)
	ret0, _ := ret[0].(*account.AccountMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAccountMemeberRoles indicates an expected call of SetAccountMemeberRoles.
func (mr *MockMemberUsecaseMockRecorder) SetAccountMemeberRoles(ctx, accountID, userID any, roles ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, accountID, userID}, roles...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAccountMemeberRoles", reflect.TypeOf((*MockMemberUsecase)(nil).SetAccountMemeberRoles), varargs...)
}

// SetMemberRoles mocks base method.
func (m *MockMemberUsecase) SetMemberRoles(ctx context.Context, memberID uint64, roles ...string) (*account.AccountMember, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, memberID}
	for _, a := range roles {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetMemberRoles", varargs...)
	ret0, _ := ret[0].(*account.AccountMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMemberRoles indicates an expected call of SetMemberRoles.
func (mr *MockMemberUsecaseMockRecorder) SetMemberRoles(ctx, memberID any, roles ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, memberID}, roles...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMemberRoles", reflect.TypeOf((*MockMemberUsecase)(nil).SetMemberRoles), varargs...)
}

// UnlinkAccountMember mocks base method.
func (m *MockMemberUsecase) UnlinkAccountMember(ctx context.Context, memberID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkAccountMember", ctx, memberID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkAccountMember indicates an expected call of UnlinkAccountMember.
func (mr *MockMemberUsecaseMockRecorder) UnlinkAccountMember(ctx, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkAccountMember", reflect.TypeOf((*MockMemberUsecase)(nil).UnlinkAccountMember), ctx, memberID)
}

// UnlinkMember mocks base method.
func (m *MockMemberUsecase) UnlinkMember(ctx context.Context, arg1 *account.Account, members ...*account.User) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, arg1}
	for _, a := range members {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnlinkMember", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkMember indicates an expected call of UnlinkMember.
func (mr *MockMemberUsecaseMockRecorder) UnlinkMember(ctx, arg1 any, members ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, arg1}, members...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkMember", reflect.TypeOf((*MockMemberUsecase)(nil).UnlinkMember), varargs...)
}
