// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/geniusrabbit/blaze-api/server/graphql/types"
	"github.com/google/uuid"
)

// AuthClient object represents an OAuth 2.0 client
type AuthClient struct {
	// ClientID is the client ID which represents unique connection indentificator
	ID        string `json:"ID"`
	AccountID uint64 `json:"accountID"`
	UserID    uint64 `json:"userID"`
	// Title of the AuthClient as himan readable name
	Title string `json:"title"`
	// Secret is the client's secret. The secret will be included in the create request as cleartext, and then
	// never again. The secret is stored using BCrypt so it is impossible to recover it. Tell your users
	// that they need to write the secret down as it will not be made available again.
	Secret string `json:"secret"`
	// RedirectURIs is an array of allowed redirect urls for the client, for example http://mydomain/oauth/callback .
	RedirectURIs []string `json:"redirectURIs,omitempty"`
	// GrantTypes is an array of grant types the client is allowed to use.
	//
	// Pattern: client_credentials|authorization_code|implicit|refresh_token
	GrantTypes []string `json:"grantTypes,omitempty"`
	// ResponseTypes is an array of the OAuth 2.0 response type strings that the client can
	// use at the authorization endpoint.
	//
	// Pattern: id_token|code|token
	ResponseTypes []string `json:"responseTypes,omitempty"`
	// Scope is a string containing a space-separated list of scope values (as
	// described in Section 3.3 of OAuth 2.0 [RFC6749]) that the client
	// can use when requesting access tokens.
	//
	// Pattern: ([a-zA-Z0-9\.\*]+\s?)+
	Scope string `json:"scope"`
	// Audience is a whitelist defining the audiences this client is allowed to request tokens for. An audience limits
	// the applicability of an OAuth 2.0 Access Token to, for example, certain API endpoints. The value is a list
	// of URLs. URLs MUST NOT contain whitespaces.
	Audience []string `json:"audience,omitempty"`
	// SubjectType requested for responses to this Client. The subject_types_supported Discovery parameter contains a
	// list of the supported subject_type values for this server. Valid types include `pairwise` and `public`.
	SubjectType string `json:"subjectType"`
	// AllowedCORSOrigins are one or more URLs (scheme://host[:port]) which are allowed to make CORS requests
	// to the /oauth/token endpoint. If this array is empty, the sever's CORS origin configuration (`CORS_ALLOWED_ORIGINS`)
	// will be used instead. If this array is set, the allowed origins are appended to the server's CORS origin configuration.
	// Be aware that environment variable `CORS_ENABLED` MUST be set to `true` for this to work.
	AllowedCORSOrigins []string `json:"allowedCORSOrigins,omitempty"`
	// Public flag tells that the client is public
	Public bool `json:"public"`
	// ExpiresAt contins the time of expiration of the client
	ExpiresAt time.Time  `json:"expiresAt"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
}

// AuthClientCreateInput is used to create a new OAuth 2.0 client
type AuthClientCreateInput struct {
	// AccountID of the auth client owner
	AccountID *uint64 `json:"accountID,omitempty"`
	// UserID of the auth client creator
	UserID *uint64 `json:"userID,omitempty"`
	// Title of the auth client as human readable name
	Title *string `json:"title,omitempty"`
	// Secret for the OAuth 2.0 client
	Secret *string `json:"secret,omitempty"`
	// RedirectURIs allowed for this client
	RedirectURIs []string `json:"redirectURIs,omitempty"`
	// GrantTypes allowed for this client
	GrantTypes []string `json:"grantTypes,omitempty"`
	// ResponseTypes allowed for this client
	ResponseTypes []string `json:"responseTypes,omitempty"`
	// Scope string for the client
	Scope *string `json:"scope,omitempty"`
	// Audience whitelist for token requests
	Audience []string `json:"audience,omitempty"`
	// SubjectType for responses to this client
	SubjectType string `json:"subjectType"`
	// AllowedCORSOrigins for this client
	AllowedCORSOrigins []string `json:"allowedCORSOrigins,omitempty"`
	// Public flag for the client
	Public *bool `json:"public,omitempty"`
	// ExpiresAt time for the client
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

type AuthClientEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *AuthClient `json:"node,omitempty"`
}

type AuthClientListFilter struct {
	ID        []string `json:"ID,omitempty"`
	UserID    []uint64 `json:"userID,omitempty"`
	AccountID []uint64 `json:"accountID,omitempty"`
	Public    *bool    `json:"public,omitempty"`
}

type AuthClientListOrder struct {
	ID         *Ordering `json:"ID,omitempty"`
	UserID     *Ordering `json:"userID,omitempty"`
	AccountID  *Ordering `json:"accountID,omitempty"`
	Title      *Ordering `json:"title,omitempty"`
	Public     *Ordering `json:"public,omitempty"`
	LastUpdate *Ordering `json:"lastUpdate,omitempty"`
}

// AuthClientPayload wrapper to access of AuthClient oprtation results
type AuthClientPayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID string `json:"clientMutationID"`
	// AuthClient ID operation result
	AuthClientID string `json:"authClientID"`
	// AuthClient object accessor
	AuthClient *AuthClient `json:"authClient,omitempty"`
}

// AuthClientUpdateInput is used to update an existing OAuth 2.0 client
type AuthClientUpdateInput struct {
	// AccountID of the auth client owner
	AccountID *uint64 `json:"accountID,omitempty"`
	// UserID of the auth client creator
	UserID *uint64 `json:"userID,omitempty"`
	// Title of the auth client as human readable name
	Title *string `json:"title,omitempty"`
	// Secret for the OAuth 2.0 client
	Secret *string `json:"secret,omitempty"`
	// RedirectURIs allowed for this client
	RedirectURIs []string `json:"redirectURIs,omitempty"`
	// GrantTypes allowed for this client
	GrantTypes []string `json:"grantTypes,omitempty"`
	// ResponseTypes allowed for this client
	ResponseTypes []string `json:"responseTypes,omitempty"`
	// Scope string for the client
	Scope *string `json:"scope,omitempty"`
	// Audience whitelist for token requests
	Audience []string `json:"audience,omitempty"`
	// SubjectType for responses to this client
	SubjectType *string `json:"subjectType,omitempty"`
	// AllowedCORSOrigins for this client
	AllowedCORSOrigins []string `json:"allowedCORSOrigins,omitempty"`
	// Public flag for the client
	Public *bool `json:"public,omitempty"`
	// ExpiresAt time for the client
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

type DirectAccessToken struct {
	ID          uint64    `json:"ID"`
	Token       string    `json:"token"`
	Description string    `json:"description"`
	UserID      *uint64   `json:"userID,omitempty"`
	AccountID   uint64    `json:"accountID"`
	CreatedAt   time.Time `json:"createdAt"`
	ExpiresAt   time.Time `json:"expiresAt"`
}

type DirectAccessTokenEdge struct {
	// Cursor for pagination
	Cursor string `json:"cursor"`
	// Node for the edge
	Node *DirectAccessToken `json:"node,omitempty"`
}

type DirectAccessTokenListFilter struct {
	ID           []uint64   `json:"ID,omitempty"`
	Token        []string   `json:"token,omitempty"`
	UserID       []uint64   `json:"userID,omitempty"`
	AccountID    []uint64   `json:"accountID,omitempty"`
	MinExpiresAt *time.Time `json:"minExpiresAt,omitempty"`
	MaxExpiresAt *time.Time `json:"maxExpiresAt,omitempty"`
}

type DirectAccessTokenListOrder struct {
	ID        *Ordering `json:"ID,omitempty"`
	Token     *Ordering `json:"token,omitempty"`
	UserID    *Ordering `json:"userID,omitempty"`
	AccountID *Ordering `json:"accountID,omitempty"`
	CreatedAt *Ordering `json:"createdAt,omitempty"`
	ExpiresAt *Ordering `json:"expiresAt,omitempty"`
}

type DirectAccessTokenPayload struct {
	// Unique identifier for the client performing the mutation
	ClientMutationID string `json:"clientMutationID"`
	// DirectAccessToken ID operation result
	Token *DirectAccessToken `json:"token,omitempty"`
}

// HistoryAction is the model for history actions.
type HistoryAction struct {
	ID         uuid.UUID          `json:"ID"`
	RequestID  string             `json:"RequestID"`
	Name       string             `json:"name"`
	Message    string             `json:"message"`
	UserID     uint64             `json:"userID"`
	AccountID  uint64             `json:"accountID"`
	ObjectType string             `json:"objectType"`
	ObjectID   uint64             `json:"objectID"`
	ObjectIDs  string             `json:"objectIDs"`
	Data       types.NullableJSON `json:"data"`
	ActionAt   time.Time          `json:"actionAt"`
}

// Edge of action history object.
type HistoryActionEdge struct {
	// The item at the end of the edge.
	Node *HistoryAction `json:"node"`
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
}

type HistoryActionListFilter struct {
	ID []uuid.UUID `json:"ID,omitempty"`
	// The request ID of the action
	RequestID []string `json:"RequestID,omitempty"`
	// The name of the action
	Name []string `json:"name,omitempty"`
	// List of users who made the action
	UserID []uint64 `json:"userID,omitempty"`
	// List of accounts that the user belongs to
	AccountID []uint64 `json:"accountID,omitempty"`
	// Type of the object that the action is performed on
	ObjectType []string `json:"objectType,omitempty"`
	// Object ID of the model that the action is performed on
	ObjectID []uint64 `json:"objectID,omitempty"`
	// Object ID string version of the model that the action is performed on
	ObjectIDs []string `json:"objectIDs,omitempty"`
}

// HistoryActionListOptions contains the options for listing history actions ordering.
type HistoryActionListOrder struct {
	ID         *Ordering `json:"ID,omitempty"`
	RequestID  *Ordering `json:"RequestID,omitempty"`
	Name       *Ordering `json:"name,omitempty"`
	UserID     *Ordering `json:"userID,omitempty"`
	AccountID  *Ordering `json:"accountID,omitempty"`
	ObjectType *Ordering `json:"objectType,omitempty"`
	ObjectID   *Ordering `json:"objectID,omitempty"`
	ObjectIDs  *Ordering `json:"objectIDs,omitempty"`
	ActionAt   *Ordering `json:"actionAt,omitempty"`
}

// HistoryActionPayload contains the information about a history action.
type HistoryActionPayload struct {
	// The client mutation id
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// The history action object ID
	ActionID uuid.UUID `json:"actionID"`
	// The action object
	Action *HistoryAction `json:"action"`
}

type InviteMemberInput struct {
	// The ID of the member to invite
	UserID uint64 `json:"userID"`
	// The roles to assign to the member
	Roles []string `json:"roles"`
	// Is the user an admin of the account
	IsAdmin bool `json:"isAdmin"`
}

// Account Member represents a member of the account
type Member struct {
	// The primary key of the Member
	ID uint64 `json:"ID"`
	// Status of Member active
	Status ApproveStatus `json:"status"`
	// User ID of the member
	UserID uint64 `json:"userID"`
	// Account ID of the member
	AccountID uint64 `json:"accountID"`
	// Is the user an admin of the account
	IsAdmin bool `json:"isAdmin"`
	// Roles of the member
	Roles     []*RBACRole `json:"roles,omitempty"`
	CreatedAt time.Time   `json:"createdAt"`
	UpdatedAt time.Time   `json:"updatedAt"`
	DeletedAt *time.Time  `json:"deletedAt,omitempty"`
}

type MemberEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *Member `json:"node,omitempty"`
}

type MemberInput struct {
	// The roles to assign to the member
	Roles []string `json:"roles"`
	// Is the user an admin of the account
	IsAdmin bool `json:"isAdmin"`
}

type MemberListFilter struct {
	ID        []uint64        `json:"ID,omitempty"`
	Status    []ApproveStatus `json:"status,omitempty"`
	UserID    []uint64        `json:"userID,omitempty"`
	AccountID []uint64        `json:"accountID,omitempty"`
	IsAdmin   *bool           `json:"isAdmin,omitempty"`
}

type MemberListOrder struct {
	ID        *Ordering `json:"ID,omitempty"`
	Status    *Ordering `json:"status,omitempty"`
	UserID    *Ordering `json:"userID,omitempty"`
	AccountID *Ordering `json:"accountID,omitempty"`
	IsAdmin   *Ordering `json:"isAdmin,omitempty"`
	CreatedAt *Ordering `json:"createdAt,omitempty"`
	UpdatedAt *Ordering `json:"updatedAt,omitempty"`
}

type MemberPayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID string `json:"clientMutationID"`
	// Member ID operation result
	MemberID uint64 `json:"memberID"`
	// Member object accessor
	Member *Member `json:"member,omitempty"`
}

type Mutation struct {
}

// Option type definition represents a single option of the user or the system.
type Option struct {
	Type     OptionType          `json:"type"`
	TargetID uint64              `json:"targetID"`
	Name     string              `json:"name"`
	Value    *types.NullableJSON `json:"value,omitempty"`
}

// The edge type for Option.
type OptionEdge struct {
	Cursor string  `json:"cursor"`
	Node   *Option `json:"node"`
}

type OptionListFilter struct {
	Type        []OptionType `json:"type,omitempty"`
	TargetID    []uint64     `json:"targetID,omitempty"`
	Name        []string     `json:"name,omitempty"`
	NamePattern []string     `json:"namePattern,omitempty"`
}

type OptionListOrder struct {
	Type     *Ordering `json:"type,omitempty"`
	TargetID *Ordering `json:"targetID,omitempty"`
	Name     *Ordering `json:"name,omitempty"`
	Value    *Ordering `json:"value,omitempty"`
}

type OptionPayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID string `json:"clientMutationId"`
	// Option name
	Name string `json:"name"`
	// Option value
	Option *Option `json:"option,omitempty"`
}

// Information for paginating
type Page struct {
	// Start after the cursor ID
	After *string `json:"after,omitempty"`
	// Start after some records
	Offset *int `json:"offset,omitempty"`
	// Page number to start at (0-based), defaults to 0 (0, 1, 2, etc.)
	StartPage *int `json:"startPage,omitempty"`
	// Maximum number of items to return
	Size *int `json:"size,omitempty"`
}

// Information for paginating
type PageInfo struct {
	// When paginating backwards, the cursor to continue.
	StartCursor string `json:"startCursor"`
	// When paginating forwards, the cursor to continue.
	EndCursor string `json:"endCursor"`
	// When paginating backwards, are there more items?
	HasPreviousPage bool `json:"hasPreviousPage"`
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
	// Total number of pages available
	Total int `json:"total"`
	// Current page number
	Page int `json:"page"`
	// Number of pages
	Count int `json:"count"`
}

type Query struct {
}

type RBACPermission struct {
	Name        string  `json:"name"`
	Object      string  `json:"object"`
	Access      string  `json:"access"`
	Fullname    string  `json:"fullname"`
	Description *string `json:"description,omitempty"`
}

// A role is a collection of permissions. A role can be a child of another role.
type RBACRole struct {
	ID          uint64  `json:"ID"`
	Name        string  `json:"name"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	//  Context is a JSON object that defines the context of the role.
	//  The context is used to determine whether the role is applicable to the object.
	//  The context is a JSON object with the following structure:
	//
	// {"cover": "system", "object": "role"}
	//
	//  where:
	// "cover" - is a name of the cover area of the object type
	// "object" - is a name of the object type <module>:<object-name>
	Context            *types.NullableJSON `json:"context,omitempty"`
	ChildRoles         []*RBACRole         `json:"childRoles,omitempty"`
	Permissions        []*RBACPermission   `json:"permissions,omitempty"`
	PermissionPatterns []string            `json:"permissionPatterns,omitempty"`
	CreatedAt          time.Time           `json:"createdAt"`
	UpdatedAt          time.Time           `json:"updatedAt"`
	DeletedAt          *time.Time          `json:"deletedAt,omitempty"`
}

// RBACRoleEdge is a connection edge type for RBACRole.
type RBACRoleEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *RBACRole `json:"node,omitempty"`
}

type RBACRoleInput struct {
	Name        *string             `json:"name,omitempty"`
	Title       *string             `json:"title,omitempty"`
	Context     *types.NullableJSON `json:"context,omitempty"`
	Permissions []string            `json:"permissions,omitempty"`
}

type RBACRoleListFilter struct {
	ID   []uint64 `json:"ID,omitempty"`
	Name []string `json:"name,omitempty"`
}

type RBACRoleListOrder struct {
	ID    *Ordering `json:"ID,omitempty"`
	Name  *Ordering `json:"name,omitempty"`
	Title *Ordering `json:"title,omitempty"`
}

// RBACRolePayload wrapper to access of RBACRole oprtation results
type RBACRolePayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID string `json:"clientMutationID"`
	// Role ID operation result
	RoleID uint64 `json:"roleID"`
	// Role object accessor
	Role *RBACRole `json:"role,omitempty"`
}

// SessionToken object represents an OAuth 2.0 / JWT session token
type SessionToken struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
	IsAdmin   bool      `json:"isAdmin"`
	Roles     []string  `json:"roles,omitempty"`
}

type SocialAccount struct {
	ID        uint64             `json:"ID"`
	UserID    uint64             `json:"userID"`
	SocialID  string             `json:"socialID"`
	Provider  string             `json:"provider"`
	Email     string             `json:"email"`
	Username  string             `json:"username"`
	FirstName string             `json:"firstName"`
	LastName  string             `json:"lastName"`
	Avatar    string             `json:"avatar"`
	Link      string             `json:"link"`
	Data      types.NullableJSON `json:"data"`
	// Social Account session object accessor
	Sessions  []*SocialAccountSession `json:"sessions,omitempty"`
	CreatedAt time.Time               `json:"createdAt"`
	UpdatedAt time.Time               `json:"updatedAt"`
	DeletedAt *time.Time              `json:"deletedAt,omitempty"`
}

type SocialAccountEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *SocialAccount `json:"node,omitempty"`
}

type SocialAccountListFilter struct {
	ID       []uint64 `json:"ID,omitempty"`
	UserID   []uint64 `json:"userID,omitempty"`
	Provider []string `json:"provider,omitempty"`
	Username []string `json:"username,omitempty"`
	Email    []string `json:"email,omitempty"`
}

type SocialAccountListOrder struct {
	ID        *Ordering `json:"ID,omitempty"`
	UserID    *Ordering `json:"userID,omitempty"`
	Provider  *Ordering `json:"provider,omitempty"`
	Email     *Ordering `json:"email,omitempty"`
	Username  *Ordering `json:"username,omitempty"`
	FirstName *Ordering `json:"firstName,omitempty"`
	LastName  *Ordering `json:"lastName,omitempty"`
}

// SocialAccountPayload wrapper to access of SocialAccount oprtation results
type SocialAccountPayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID string `json:"clientMutationID"`
	// Social Account ID operation result
	SocialAccountID uint64 `json:"socialAccountID"`
	// Social Account object accessor
	SocialAccount *SocialAccount `json:"socialAccount,omitempty"`
}

type SocialAccountSession struct {
	// The unique name of the session to destinguish between different sessions with different scopes
	Name            string     `json:"name"`
	SocialAccountID uint64     `json:"socialAccountID"`
	TokenType       string     `json:"tokenType"`
	AccessToken     string     `json:"accessToken"`
	RefreshToken    string     `json:"refreshToken"`
	Scope           []string   `json:"scope,omitempty"`
	CreatedAt       time.Time  `json:"createdAt"`
	UpdatedAt       time.Time  `json:"updatedAt"`
	ExpiresAt       *time.Time `json:"expiresAt,omitempty"`
	DeletedAt       *time.Time `json:"deletedAt,omitempty"`
}

// Simple response type for the API
type StatusResponse struct {
	// Unique identifier for the client performing the mutation
	ClientMutationID string `json:"clientMutationID"`
	// The status of the response
	Status ResponseStatus `json:"status"`
	// The message of the response
	Message *string `json:"message,omitempty"`
}

type OptionType string

const (
	OptionTypeUndefined OptionType = "UNDEFINED"
	OptionTypeUser      OptionType = "USER"
	OptionTypeAccount   OptionType = "ACCOUNT"
	OptionTypeSystem    OptionType = "SYSTEM"
)

var AllOptionType = []OptionType{
	OptionTypeUndefined,
	OptionTypeUser,
	OptionTypeAccount,
	OptionTypeSystem,
}

func (e OptionType) IsValid() bool {
	switch e {
	case OptionTypeUndefined, OptionTypeUser, OptionTypeAccount, OptionTypeSystem:
		return true
	}
	return false
}

func (e OptionType) String() string {
	return string(e)
}

func (e *OptionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OptionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OptionType", str)
	}
	return nil
}

func (e OptionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OptionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OptionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Constants of the response status
type ResponseStatus string

const (
	// Success status of the response
	ResponseStatusSuccess ResponseStatus = "SUCCESS"
	// Error status of the response
	ResponseStatusError ResponseStatus = "ERROR"
)

var AllResponseStatus = []ResponseStatus{
	ResponseStatusSuccess,
	ResponseStatusError,
}

func (e ResponseStatus) IsValid() bool {
	switch e {
	case ResponseStatusSuccess, ResponseStatusError:
		return true
	}
	return false
}

func (e ResponseStatus) String() string {
	return string(e)
}

func (e *ResponseStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ResponseStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ResponseStatus", str)
	}
	return nil
}

func (e ResponseStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ResponseStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ResponseStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
